#!/bin/bash

echo "==================================="
echo "QFN32 测试方案（不需要编译）"
echo "==================================="

echo ""
echo "方案1：直接使用原始hex"
echo "------------------------"
echo "文件：original_working.hex (8196 bytes)"
echo "特点："
echo "  - PC6 输出 100kHz PWM ✓ (已验证)"
echo "  - 使用 PC4 切换（QFN32上可能没有此引脚）"
echo "  - 至少能验证 PC6 PWM 是否正常"
echo ""
echo "测试步骤："
echo "  1. 烧录 original_working.hex"
echo "  2. 用示波器测 PC6 (Pin 23) - 应该有100kHz方波"
echo "  3. 如果有方波 = MCU和基础系统正常"
echo ""

echo "方案2：验证GPIO基础功能"
echo "------------------------"
echo "既然PC6的PWM能工作，说明："
echo "  - MCU正常"
echo "  - 时钟正常"
echo "  - Flash烧写正常"
echo ""
echo "GPIO不工作可能原因："
echo "  1. LED硬件连接问题"
echo "  2. PC0/PC1引脚问题"
echo "  3. 电源不足"
echo ""

echo "方案3：硬件排查建议"
echo "------------------------"
echo "1. 测量电压："
echo "   - VDD应该是3.3V"
echo "   - PC0/PC1静态电平"
echo ""
echo "2. LED检查："
echo "   - LED是否正确连接"
echo "   - 限流电阻是否合适"
echo "   - 手动给PC0/PC1加低电平看LED是否亮"
echo ""

echo "==================================="
echo "结论：先确认硬件，再改软件"
echo "==================================="

ls -la *.hex | grep -E "original|qfn32"